from pipeline import SingleClickIcorePipeline
from utils import PacsConfiguration, RunDirs, SingleClickResult, Spreadsheet


def singleclickicore(
    pacs_list: list[PacsConfiguration],
    query_spreadsheet: Spreadsheet,
    application_aet: str,
    sas_url: str | None,
    project_name: str,
    output_dir: str,
    input_file: str,
    appdata_dir: str | None = None,
    filter_script: str | None = None,
    date_window_days: int = 0,
    anonymizer_script: str | None = None,
    deid_pixels: bool = False,
    lookup_table: str | None = None,
    apply_default_filter_script: bool = True,
    mapping_file_path: str | None = None,
    to_keep_list: list[str] | None = None,
    to_remove_list: list[str] | None = None,
    columns_to_drop: list[str] | None = None,
    columns_to_deid: list[str] | None = None,
    debug: bool = False,
    run_dirs: RunDirs | None = None,
    skip_export: bool = False,
    sc_pdf_output_dir: str | None = None,
    use_fallback_query: bool = False,
    storescp_port: int = 50001,
    deferred_delivery: bool = False,
    deferred_delivery_timeout: int = 172800,
    deid_engine: str = "ctp",
) -> SingleClickResult:
    return SingleClickIcorePipeline(
        sas_url=sas_url,
        project_name=project_name,
        input_file=input_file,
        to_keep_list=to_keep_list,
        to_remove_list=to_remove_list,
        columns_to_drop=columns_to_drop,
        columns_to_deid=columns_to_deid,
        skip_export=skip_export,
        pacs_list=pacs_list,
        query_spreadsheet=query_spreadsheet,
        application_aet=application_aet,
        output_dir=output_dir,
        appdata_dir=appdata_dir,
        filter_script=filter_script,
        date_window_days=date_window_days,
        anonymizer_script=anonymizer_script,
        deid_pixels=deid_pixels,
        lookup_table=lookup_table,
        debug=debug,
        run_dirs=run_dirs,
        apply_default_filter_script=apply_default_filter_script,
        mapping_file_path=mapping_file_path,
        sc_pdf_output_dir=sc_pdf_output_dir,
        use_fallback_query=use_fallback_query,
        storescp_port=storescp_port,
        deferred_delivery=deferred_delivery,
        deferred_delivery_timeout=deferred_delivery_timeout,
    ).run()
