from django.urls import path

from . import views

urlpatterns = [
    path('headerquery/', views.HeaderQueryView.as_view(), name='header_query'),
    path('header_extract/', views.HeaderExtractView.as_view(), name='header_extract'),
    path('imagedeid/', views.ImageDeIdentificationView.as_view(), name='image_deid'),
    path('imagequery/', views.ImageQueryView.as_view(), name='image_query'),
    path('textdeid/', views.TextDeIdentificationView.as_view(), name='text_deid'),
    path('image_export/', views.ImageExportView.as_view(), name='image_export'),
    path('tasks/', views.TaskListView.as_view(), name='task_list'),
    path('run_header_query/', views.run_header_query, name='run_header_query'),
    path('run_header_extract/', views.run_header_extract, name='run_header_extract'),
    path('run_deid/', views.run_deid, name='run_deid'),
    path('run_text_deid/', views.run_text_deid, name='run_text_deid'),
    path('run_query/', views.run_query, name='run_query'),
    path('run_export/', views.run_export, name='run_export'),
    path('run_general_module/', views.run_general_module, name='run_general_module'),
    path('task_progress/', views.TaskProgressView.as_view(), name='task_progress'),
    path('get_log_content/', views.get_log_content, name='get_log_content'),
    path('api/task_status/<int:project_id>/', views.task_status, name='task_status'),
    path('settings/general/', views.GeneralSettingsView.as_view(), name='general_settings'),
    path('test_pacs_connection/', views.test_pacs_connection, name='test_pacs_connection'),
    path('settings/dicom_header_qr/', views.DicomHeaderQRSettingsView.as_view(), name='dicom_header_qr_settings'),
    path('settings/local_header_extraction/', views.LocalHeaderExtractionSettingsView.as_view(), name='local_header_extraction_settings'),
    path('settings/image_qr/', views.ImageQRSettingsView.as_view(), name='image_qr_settings'),
    path('settings/image_deid/', views.ImageDeIdentificationSettingsView.as_view(), name='image_deid_settings'),
    path('settings/text_deid/', views.TextDeIdentificationSettingsView.as_view(), name='text_deid_settings'),
    path('settings/admin/', views.AdminSettingsView.as_view(), name='admin_settings'),
    path('settings/new_module/', views.NewModuleView.as_view(), name='new_module'),
    path('save_settings/', views.save_settings, name='save_settings'),
    path('load_settings/', views.load_settings, name='load_settings'),
    path('load_admin_settings/', views.load_admin_settings, name='load_admin_settings'),
    path('save_admin_settings/', views.save_admin_settings, name='save_admin_settings'),
    path('get_protocol_settings/<str:protocol_id>/', views.get_protocol_settings, name='get_protocol_settings'),
    path('verify_admin_password/', views.verify_admin_password, name='verify_admin_password'),
    path('task_list/', views.TaskListView.as_view(), name='task_list'),
    path('delete_task/<int:task_id>/', views.delete_task, name='delete_task'),
    path('upload_module/', views.upload_module, name='upload_module'),
    path('get_modules/', views.get_modules, name='get_modules'),
    path('<str:module_name>/', views.GeneralModuleView.as_view(), name='general_module'),
    path('delete_module/<int:module_id>/', views.delete_module, name='delete_module'),
    path('toggle_module_status/<int:module_id>/', views.toggle_module_status, name='toggle_module_status'),
]
