/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/run_deid/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runDeid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/run_export/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/run_header_extract/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runHeaderExtract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/run_imagedeidexport/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runImageDeidExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/run_query/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runQuery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/run_singleclickicore/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runSingleClickICore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/run_text_deid/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["runTextDeid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FilterEntry */
        FilterEntry: {
            /** Action */
            action: string;
            /** Tag */
            tag: string;
            /**
             * Value
             * @default
             */
            value?: string;
        };
        /**
         * PacsConfigEntry
         * @description An entry of settings.json's pacs_configs (forwarded by the frontend);
         *     extra keys are tolerated since the settings file is free-form.
         */
        PacsConfigEntry: {
            /** Ae */
            ae: string;
            /** Ip */
            ip: string;
            /** Port */
            port: number | string;
        };
        /** RunDeidRequest */
        RunDeidRequest: {
            /** Acc Col */
            acc_col: string;
            /** Application Aet */
            application_aet: string;
            /**
             * Apply Default Ctp Filter Script
             * @default true
             */
            apply_default_ctp_filter_script?: boolean;
            /** Date Col */
            date_col: string;
            /** Date Shift Days */
            date_shift_days: number | string;
            /**
             * Date Window
             * @default 0
             */
            date_window?: number;
            /**
             * Deid Engine
             * @default ctp
             * @enum {string}
             */
            deid_engine?: "ctp" | "rust";
            /**
             * Deid Pixels
             * @default false
             */
            deid_pixels?: boolean;
            /** General Filters */
            general_filters: components["schemas"]["FilterEntry"][];
            /**
             * Image Source
             * @enum {string}
             */
            image_source: "LOCAL" | "PACS";
            /** Input File */
            input_file: string;
            /** Input Folder */
            input_folder: string;
            /**
             * Mapping File Path
             * @default
             */
            mapping_file_path?: string;
            /** Modality Filters */
            modality_filters: {
                [key: string]: components["schemas"]["FilterEntry"][];
            };
            /** Mrn Col */
            mrn_col: string;
            /** Output Folder */
            output_folder: string;
            /** Pacs Configs */
            pacs_configs: components["schemas"]["PacsConfigEntry"][];
            /**
             * Remove Curves
             * @default false
             */
            remove_curves?: boolean;
            /**
             * Remove Overlays
             * @default false
             */
            remove_overlays?: boolean;
            /**
             * Remove Private
             * @default false
             */
            remove_private?: boolean;
            /**
             * Remove Unspecified
             * @default false
             */
            remove_unspecified?: boolean;
            /**
             * Sc Pdf Output Dir
             * @default
             */
            sc_pdf_output_dir?: string;
            /**
             * Scheduled Time
             * @default null
             */
            scheduled_time?: string | null;
            /** Site Id */
            site_id: string;
            /** Study Name */
            study_name: string;
            /** Tags To Dateshift */
            tags_to_dateshift: string;
            /** Tags To Keep */
            tags_to_keep: string;
            /** Tags To Randomize */
            tags_to_randomize: string;
            /**
             * Use Fallback Query
             * @default false
             */
            use_fallback_query?: boolean;
            /**
             * Use Mapping File
             * @default false
             */
            use_mapping_file?: boolean;
        };
        /** RunExportRequest */
        RunExportRequest: {
            /** Input Folder */
            input_folder: string;
            /** Sas Url */
            sas_url: string;
            /** Study Name */
            study_name: string;
        };
        /** RunHeaderExtractRequest */
        RunHeaderExtractRequest: {
            /**
             * Extract All Headers
             * @default false
             */
            extract_all_headers?: boolean;
            /**
             * Headers To Extract
             * @default null
             */
            headers_to_extract?: string | null;
            /** Input Folder */
            input_folder: string;
            /** Output Folder */
            output_folder: string;
            /** Study Name */
            study_name: string;
        };
        /** RunImageDeidExportRequest */
        RunImageDeidExportRequest: {
            /** Acc Col */
            acc_col: string;
            /** Application Aet */
            application_aet: string;
            /**
             * Apply Default Ctp Filter Script
             * @default true
             */
            apply_default_ctp_filter_script?: boolean;
            /** Date Col */
            date_col: string;
            /** Date Shift Days */
            date_shift_days: number | string;
            /**
             * Date Window
             * @default 0
             */
            date_window?: number;
            /**
             * Deid Engine
             * @default ctp
             * @enum {string}
             */
            deid_engine?: "ctp" | "rust";
            /**
             * Deid Pixels
             * @default false
             */
            deid_pixels?: boolean;
            /** General Filters */
            general_filters: components["schemas"]["FilterEntry"][];
            /** Input File */
            input_file: string;
            /**
             * Mapping File Path
             * @default
             */
            mapping_file_path?: string;
            /** Modality Filters */
            modality_filters: {
                [key: string]: components["schemas"]["FilterEntry"][];
            };
            /** Mrn Col */
            mrn_col: string;
            /** Output Folder */
            output_folder: string;
            /** Pacs Configs */
            pacs_configs: components["schemas"]["PacsConfigEntry"][];
            /**
             * Remove Curves
             * @default false
             */
            remove_curves?: boolean;
            /**
             * Remove Overlays
             * @default false
             */
            remove_overlays?: boolean;
            /**
             * Remove Private
             * @default false
             */
            remove_private?: boolean;
            /**
             * Remove Unspecified
             * @default false
             */
            remove_unspecified?: boolean;
            /** Sas Url */
            sas_url: string;
            /**
             * Sc Pdf Output Dir
             * @default
             */
            sc_pdf_output_dir?: string;
            /**
             * Scheduled Time
             * @default null
             */
            scheduled_time?: string | null;
            /** Site Id */
            site_id: string;
            /** Study Name */
            study_name: string;
            /** Tags To Dateshift */
            tags_to_dateshift: string;
            /** Tags To Keep */
            tags_to_keep: string;
            /** Tags To Randomize */
            tags_to_randomize: string;
            /**
             * Use Fallback Query
             * @default false
             */
            use_fallback_query?: boolean;
            /**
             * Use Mapping File
             * @default false
             */
            use_mapping_file?: boolean;
        };
        /** RunQueryRequest */
        RunQueryRequest: {
            /** Acc Col */
            acc_col: string;
            /** Application Aet */
            application_aet: string;
            /** Date Col */
            date_col: string;
            /**
             * Date Window
             * @default 0
             */
            date_window?: number;
            /** General Filters */
            general_filters: components["schemas"]["FilterEntry"][];
            /** Input File */
            input_file: string;
            /** Modality Filters */
            modality_filters: {
                [key: string]: components["schemas"]["FilterEntry"][];
            };
            /** Mrn Col */
            mrn_col: string;
            /** Output Folder */
            output_folder: string;
            /** Pacs Configs */
            pacs_configs: components["schemas"]["PacsConfigEntry"][];
            /**
             * Scheduled Time
             * @default null
             */
            scheduled_time?: string | null;
            /** Study Name */
            study_name: string;
            /**
             * Use Fallback Query
             * @default false
             */
            use_fallback_query?: boolean;
        };
        /** RunResponse */
        RunResponse: {
            /** Log Path */
            log_path: string;
            /**
             * Message
             * @default null
             */
            message?: string | null;
            /** Project Id */
            project_id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "error";
        };
        /** RunSingleClickRequest */
        RunSingleClickRequest: {
            /** Application Aet */
            application_aet: string;
            /**
             * Apply Default Ctp Filter Script
             * @default true
             */
            apply_default_ctp_filter_script?: boolean;
            /** Column Actions */
            column_actions: {
                [key: string]: "keep" | "deid" | "drop";
            };
            /**
             * Date Window
             * @default 0
             */
            date_window?: number;
            /**
             * Export To Azure
             * @default true
             */
            export_to_azure?: boolean;
            /**
             * General Filters
             * @default []
             */
            general_filters?: components["schemas"]["FilterEntry"][];
            /** Input File */
            input_file: string;
            /**
             * Mapping File Path
             * @default
             */
            mapping_file_path?: string;
            /**
             * Modality Filters
             * @default {}
             */
            modality_filters?: {
                [key: string]: components["schemas"]["FilterEntry"][];
            };
            /** Output Folder */
            output_folder: string;
            /** Pacs Configs */
            pacs_configs: components["schemas"]["PacsConfigEntry"][];
            /**
             * Sas Url
             * @default
             */
            sas_url?: string;
            /**
             * Sc Pdf Output Dir
             * @default
             */
            sc_pdf_output_dir?: string;
            /**
             * Scheduled Time
             * @default null
             */
            scheduled_time?: string | null;
            /** Study Name */
            study_name: string;
            /**
             * Text To Keep
             * @default
             */
            text_to_keep?: string;
            /**
             * Text To Remove
             * @default
             */
            text_to_remove?: string;
            /**
             * Use Fallback Query
             * @default false
             */
            use_fallback_query?: boolean;
            /**
             * Use Mapping File
             * @default false
             */
            use_mapping_file?: boolean;
        };
        /** RunTextDeidRequest */
        RunTextDeidRequest: {
            /** Column Actions */
            column_actions: {
                [key: string]: "keep" | "deid" | "drop";
            };
            /**
             * Date Shift Days
             * @default 0
             */
            date_shift_days?: number | string;
            /** Input File */
            input_file: string;
            /** Output Folder */
            output_folder: string;
            /**
             * Scheduled Time
             * @default null
             */
            scheduled_time?: string | null;
            /** Study Name */
            study_name: string;
            /**
             * Text To Keep
             * @default
             */
            text_to_keep?: string;
            /**
             * Text To Remove
             * @default
             */
            text_to_remove?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    runDeid: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunDeidRequest"];
            };
        };
        responses: {
            /** @description Job created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
        };
    };
    runExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunExportRequest"];
            };
        };
        responses: {
            /** @description Job created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
        };
    };
    runHeaderExtract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunHeaderExtractRequest"];
            };
        };
        responses: {
            /** @description Job created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
        };
    };
    runImageDeidExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunImageDeidExportRequest"];
            };
        };
        responses: {
            /** @description Job created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
        };
    };
    runQuery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunQueryRequest"];
            };
        };
        responses: {
            /** @description Job created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
        };
    };
    runSingleClickICore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunSingleClickRequest"];
            };
        };
        responses: {
            /** @description Job created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
        };
    };
    runTextDeid: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunTextDeidRequest"];
            };
        };
        responses: {
            /** @description Job created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
        };
    };
}
