# Generated by Django 4.2.16 on 2025-03-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_source', models.CharField(choices=[('LOCAL', 'Local folder'), ('PACS', 'PACS')], max_length=10)),
                ('input_folder', models.CharField(max_length=255)),
                ('output_folder', models.CharField(max_length=255)),
                ('pacs_configs', models.JSONField(default=list)),
                ('application_aet', models.CharField(blank=True, max_length=255, null=True)),
                ('ctp_dicom_filter', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('IMAGE_DEID', 'Image De-identification'), ('IMAGE_QUERY', 'Image Query'), ('HEADER_QUERY', 'Header Query'), ('TEXT_DEID', 'Text De-identification'), ('IMAGE_EXPORT', 'Image Export'), ('TEXT_EXTRACT', 'Text Extraction')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('parameters', models.JSONField()),
            ],
            options={
                'db_table': 'deid_tasks',
            },
        ),
    ]
