# Generated by Django 4.2.16 on 2024-11-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_source', models.CharField(choices=[('LOCAL', 'Local folder'), ('PACS', 'PACS')], max_length=10)),
                ('input_folder', models.CharField(max_length=255)),
                ('output_folder', models.CharField(max_length=255)),
                ('ctp_dicom_filter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameters', models.JSONField()),
            ],
            options={
                'db_table': 'deid_tasks',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_image_source', models.CharField(default='LOCAL', max_length=10)),
                ('default_tags_to_keep', models.TextField(blank=True)),
                ('default_tags_to_dateshift', models.TextField(blank=True)),
                ('default_tags_to_randomize', models.TextField(blank=True)),
                ('default_date_shift_days', models.IntegerField(blank=True, null=True)),
                ('id_generation_method', models.CharField(default='UNIQUE', max_length=10)),
                ('general_filters', models.JSONField(default=list)),
                ('modality_filters', models.JSONField(default=dict)),
            ],
        ),
    ]
