# Generated by Django 5.1.6 on 2025-02-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("IMAGE_DEID", "Image De-identification"),
                    ("IMAGE_QUERY", "Image Query"),
                    ("HEADER_QUERY", "Header Query"),
                    ("TEXT_DEID", "Text De-identification"),
                    ("TEXT_EXTRACT", "Text Extraction"),
                ],
                max_length=20,
            ),
        ),
    ]
