# Generated by Django 6.0.5 on 2026-06-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_project_celery_task_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.AlterField(
            model_name='project',
            name='task_type',
            field=models.CharField(choices=[('IMAGE_DEID', 'Image Deidentification'), ('IMAGE_QUERY', 'Image Query'), ('HEADER_EXTRACT', 'Header Extract'), ('TEXT_DEID', 'Text Deidentification'), ('IMAGE_EXPORT', 'Image Export'), ('IMAGE_DEID_EXPORT', 'Image Deidentification and Export'), ('SINGLE_CLICK_ICORE', 'Single Click iCore')], max_length=25),
        ),
    ]
